feat: task detail page
couchbaselabs/mobile-training-todo pull request #205
Opened 2021-03-24 08:56 UTC by jayahariv

* add task detail page with segmented control for choosing to-(dictionary/json)
* add more key-values to the document
* complete/not-complete switch

<img width="481" alt="Screen Shot 2021-03-24 at 1 50 31 AM" src="https://user-images.githubusercontent.com/10448770/112282106-038a6b80-8c44-11eb-9f6a-ab698ee38bca.png">
<img width="485" alt="Screen Shot 2021-03-24 at 1 50 58 AM" src="https://user-images.githubusercontent.com/10448770/112282126-09804c80-8c44-11eb-9b75-e4a20fc694a5.png">

2021-03-25 02:03 UTC, pasin requested changes

2021-03-25 02:03 UTC, pasin commented on swift/Todo/TasksViewController.swift
> +        self.performSegue(withIdentifier: "showTaskDetail", sender: self)
Can you keep the same behavior when tapping the row to check and uncheck? Show the detail using edit action should be enough.

2021-03-26 03:00 UTC, pasin approved these changes

2021-03-26 03:00 UTC, pasin commented
It would be nice if you change the color of the detail so it can be different from the log button.

2021-03-26 03:47 UTC, merged

2021-03-30 02:56 UTC, jayahariv commented
objc > https://github.com/couchbaselabs/mobile-training-todo/commit/74692f1ce11f10b8ff749baf615a2684bab47b34